
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD MUL NUM PARA PARF SUB\n    S : Exp\n    \n    Exp : Exp ADD Termo\n    \n    Exp : Exp SUB Termo\n    \n    Exp : Termo\n    \n    Termo : Termo MUL Fator\n    \n    Termo : Fator\n    \n    Fator : PARA Exp PARF\n    \n    Fator : NUM\n    '
    
_lr_action_items = {'PARA':([0,5,7,8,9,],[5,5,5,5,5,]),'NUM':([0,5,7,8,9,],[6,6,6,6,6,]),'$end':([1,2,3,4,6,11,12,13,14,],[0,-1,-4,-6,-8,-2,-3,-5,-7,]),'ADD':([2,3,4,6,10,11,12,13,14,],[7,-4,-6,-8,7,-2,-3,-5,-7,]),'SUB':([2,3,4,6,10,11,12,13,14,],[8,-4,-6,-8,8,-2,-3,-5,-7,]),'PARF':([3,4,6,10,11,12,13,14,],[-4,-6,-8,14,-2,-3,-5,-7,]),'MUL':([3,4,6,11,12,13,14,],[9,-6,-8,9,9,-5,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'Exp':([0,5,],[2,10,]),'Termo':([0,5,7,8,],[3,3,11,12,]),'Fator':([0,5,7,8,9,],[4,4,4,4,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> Exp','S',1,'p_geral','exp_sin_val.py',8),
  ('Exp -> Exp ADD Termo','Exp',3,'p_exp_add','exp_sin_val.py',15),
  ('Exp -> Exp SUB Termo','Exp',3,'p_exp_sub','exp_sin_val.py',22),
  ('Exp -> Termo','Exp',1,'p_exp_termo','exp_sin_val.py',29),
  ('Termo -> Termo MUL Fator','Termo',3,'p_exp_mul','exp_sin_val.py',36),
  ('Termo -> Fator','Termo',1,'p_exp_fator','exp_sin_val.py',43),
  ('Fator -> PARA Exp PARF','Fator',3,'p_exp_par','exp_sin_val.py',50),
  ('Fator -> NUM','Fator',1,'p_exp_num','exp_sin_val.py',57),
]
